### ISSUE TITLE
Corsair H100i Platinum: handling HD and LL fans

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/liquidctl-device-data#2]
@MarshallAsch 

> Without swapping out the fans the H100i Platinum cooler has 24 LEDs 16 on the pump and 4 on each of the 2 ML type fans (the HD fans have 12 LEDs each, and the LL fans have 16 LEDs each).<sup>[[1]](https://github.com/jonasmalacofilho/liquidctl-device-data/blob/master/Corsair%20H100i%20RGB%20Platinum/04%20-%20capture%20-%20marshallasch/protocol.md#set-leds-to-specific-colors)</sup>

How does this work within iCue: is the device able to somehow detect this situation, or does the user need to specify it in the software?

On the protocol side, do we simply send as many colors as there are LEDs in total?  Or if, for instance, the first fan (from the point of view of the protocol) has 4 LEDs, and second 16, do we need to pad the first fan to 16 colors?

Finally, can we send an arbitrary number of colors, say for 64 LEDs?  I'm asking this because being able to send more LEDs than necessary could simplify fixing the implementation for the PRO XT coolers (which come without LED fans; jonasmalacofilho/liquidctl#149).

**Comment by MarshallAsch** [comment]
in iCue there is a drop down option for selecting a fan type (it will set both fans to the same type)

I was messing around with that setting because why not, and it still worked when I selected any type of fan configuration. And the only thing that it changed in the dumps was the number of set LEDs commands that were sent. 

My tests with sending more values then there are LEDs seemed to work fine and it also worked when I only sent one LED command (I have 24 LEDs). The only thing is that any unset values still default to being off. 


> Finally, can we send an arbitrary number of colors

yes. 

> do we need to pad the first fan.

I would assume yes, I will also try testing this in the morning.

**Comment by jonasmalacofilho** [comment]
That's nice, thanks for looking into this.

**Comment by MarshallAsch** [comment]
I looked into that, if there are fans that have more LEDs connected then you  do not pad the LED positions it seems to work on its own and still just uses the values sequentially.

**Comment by jonasmalacofilho** [comment]
Makes sense, thanks.
